<?php
$labels = array(
    'name'                     => esc_html__( 'Surveys', 'control-listings' ),
    'singular_name'            => esc_html__( 'Survey', 'control-listings' ),
    'add_new'                  => esc_html__( 'Add New', 'control-listings' ),
    'add_new_item'             => esc_html__( 'Add New Survey', 'control-listings' ),
    'edit_item'                => esc_html__( 'Edit Survey', 'control-listings' ),
    'new_item'                 => esc_html__( 'New Survey', 'control-listings' ),
    'view_item'                => esc_html__( 'View Survey', 'control-listings' ),
    'view_items'               => esc_html__( 'View Surveys', 'control-listings' ),
    'search_items'             => esc_html__( 'Search Surveys', 'control-listings' ),
    'not_found'                => esc_html__( 'No surveys found.', 'control-listings' ),
    'not_found_in_trash'       => esc_html__( 'No surveys found in Trash.', 'control-listings' ),
    'parent_item_colon'        => esc_html__( 'Parent Survey:', 'control-listings' ),
    'all_items'                => esc_html__( 'All Surveys', 'control-listings' ),
    'archives'                 => esc_html__( 'Survey Archives', 'control-listings' ),
    'attributes'               => esc_html__( 'Survey Order', 'control-listings' ),
    'insert_into_item'         => esc_html__( 'Insert into survey', 'control-listings' ),
    'uploaded_to_this_item'    => esc_html__( 'Uploaded to this survey', 'control-listings' ),
    'featured_image'           => esc_html__( 'Featured image', 'control-listings' ),
    'set_featured_image'       => esc_html__( 'Set featured image', 'control-listings' ),
    'remove_featured_image'    => esc_html__( 'Remove featured image', 'control-listings' ),
    'use_featured_image'       => esc_html__( 'Use as featured image', 'control-listings' ),
    'menu_name'                => esc_html__( 'Online Survey', 'control-listings' ),
    'filter_items_list'        => esc_html__( 'Filter surveys list', 'control-listings' ),
    'filter_by_date'           => esc_html__( '', 'control-listings' ),
    'items_list_navigation'    => esc_html__( 'Surveys list navigation', 'control-listings' ),
    'items_list'               => esc_html__( 'Surveys list', 'control-listings' ),
    'item_published'           => esc_html__( 'Survey published.', 'control-listings' ),
    'item_published_privately' => esc_html__( 'Survey published privately.', 'control-listings' ),
    'item_reverted_to_draft'   => esc_html__( 'Survey reverted to draft.', 'control-listings' ),
    'item_scheduled'           => esc_html__( 'Survey scheduled.', 'control-listings' ),
    'item_updated'             => esc_html__( 'Survey updated.', 'control-listings' ),
    'text_domain'              => 'control-listings',
);

return array(
    'labels' => $labels,
    'public' => true,
    'publicly_queryable' => true,
    'show_ui' => true, 
    'show_in_menu' => 'online-survey', 
    'menu_icon' => 'dashicons-feedback',
    'query_var' => true,
    'has_archive'         => 'surveys',
    'rest_base'           => 'surveys',
    'capability_type' => 'page',
    'hierarchical' => true,
    'menu_position' => null,
    'supports' => array( 'title', 'editor', 'thumbnail', 'excerpt', 'page-attributes' ),
    'rewrite'             => [
        'slug'       => 'survey',
        'with_front' => false,
    ],
 ); 